<?php

function hubspot_menu()
{
    $items = array();
    
    $items['admin/config/hubspot'] = array(
        'title' => 'HubSpot integration settings',
        'description' => 'Set up HubSpot integration and leads insertion.',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('hubspot_admin_settings'),
        'access arguments' => array('administer site configuration'),
        'type' => MENU_NORMAL_ITEM,
        'file' => 'hubspot.admin.inc'
    );
    
    return $items;
}

/**
 * Intercept the WebForm submission and send it off to HubSpot.
 */
function hubspot_webform_submission_insert($node, $submission)
{
    if ($submission->is_draft == 1)
        return;
    
    // Now, $submission->data is an array indexed by component ID.
    // We must find the matching field names.
    $values = array();
    
    $hubSpotURL = '';
    foreach ($submission->data as $cid => $data)
    {
        if ($node->webform['components'][$cid]['type'] == 'hubspot_url')
        {
            $hubSpotURL = $data['value'][0];
            continue; // omit HubSpot URL from POST
        }
        
        $component = $node->webform['components'][$cid]['form_key'];
        $values[$component] = implode(',', $data['value']);
    }
    
    if (empty($hubSpotURL))
    {
        // We're only interested in forms with HubSpot URLs to POST to
        return;
    }
    
    // These fields must be submitted with each request
    $values['UserToken'] = isset($_COOKIE['hubspotutk']) ? $_COOKIE['hubspotutk'] : '';
    $values['IPAddress'] = $_SERVER['REMOTE_ADDR'];
    
    $hapi = new HAPILeads();
    
    $hapi->setHAPIKey(variable_get('hubspot_apikey', ''));
    $r = $hapi->executeInsertLead($hubSpotURL, $values);
    
    if (empty($r['Error']))
    {
        watchdog('hubspot', strip_tags($r['Data']), null, WATCHDOG_INFO);
    }
    else
    {
        watchdog('hubspot', 'cURL error when submitting HubSpot data: @error',
                 array('@error' => $r['ErrorMessage']), WATCHDOG_ERROR);
    }
}

/**
 * Create a WebForm component to contain the form's HubSpot POST URL.
 */
function hubspot_webform_component_info()
{
    return array(
        'hubspot_url' => array(
            'label' => t('HubSpot POST URL'),
            'description' => t('A HubSpot API POST URL, to submit a form\'s contents to HubSpot Leads.'),
            'features' => array(
                'csv' => false,
                'email' => false,
                'title_display' => false,
                'required' => false
            )
        )
    );
}

function _webform_defaults_hubspot_url()
{
    return array(
        'name' => 'HubSpot POST URL',
        'form_key' => 'hubspot',
        'pid' => 0,
        'weight' => 0,
        'value' => '',
        'extra' => array(
        ),
    );
}

function _webform_edit_hubspot_url($component)
{
    $form = array();
    
    // Disable Description box
    $form['extra']['description'] = array();
    
    $form['value'] = array(
        '#type' => 'textfield',
        '#title' => t('HubSpot POST URL'),
        '#description' => t('The API POST URL provided under HubSpot\'s Lead API settings for this form.'),
        '#default_value' => $component['value']
    );
    
    // Hide display options
    $form['display'] = array('#type' => 'markup');
    
    $form['name'] = array(
        '#type' => 'textfield',
        '#default_value' => $component['name'],
        '#title' => t('Label'),
        '#description' => t('The name of this field. This field will not be displayed to users submitting the form.'),
        '#required' => TRUE,
        '#weight' => -10,
        '#maxlength' => 255,
    );
    
    return $form;
}

/**
 * Implements _webform_render_component().
 */
function _webform_render_hubspot_url($component, $value = NULL)
{
    $element = array(
        '#type' => 'hidden',
        '#title' => check_plain($component['name']),
        '#default_value' => check_url($component['value']),
        '#weight' => $component['weight'],
    );
    
    if (isset($value[0]))
    {
        $element['#default_value'] = $value[0];
    }

    return $element;
}

function _webform_display_hubspot_url($component, $value, $format = 'html')
{
    return array();
}

function hubspot_help($path, $arg)
{
    $output = '';
    switch($path)
    {
        case 'admin/help#hubspot':
            $output .= '<h3>' . t('About') . '</h3>';
            $output .= '<p>' . t('The HubSpot module provides leads integration with the HubSpot API, allowing forms created with the WebForm module to submit their data to HubSpot for leads tracking.') . '</p>';
            
            $output .= '<h3>' . t('Sending a form to HubSpot') . '</h3>';
            $output .= '<p>' . t('To have a form\'s data sent to HubSpot for leads tracking, complete the following steps:') . '</p>';
            $output .= '<ul>';
            $output .= '<li>' . t('Log in to your HubSpot account and visit the Settings page. Click the HubSpot Lead API link under Lead Management.') . '</li>';
            $output .= '<li>' . t('Press Add New Form and specify the form name, email list, and lead nurturing campaign as desired.') . '</li>';
            $output .= '<li>' . t('Submit the form. HubSpot will now provide an API POST URL; save this somewhere.') . '</li>';
            $output .= '<li>' . t('In your Drupal admin, use the Add content page to create a new Webform. Enter as many questions ("components") as you\'d like.') . '</li>';
            $output .= '<li>' . t('Finally, create a component named "hubspot" with the type "HubSpot POST URL". Supply the API POST URL in the box provided and save the form.') . '</li>';
            $output .= '</ul>';
            $output .= '<p>' . t('The webform will now automatically send any submissions directly to HubSpot via the POST URL you provided. You may customize, theme, or alter the form as much as you like, so long as the HubSpot POST URL field remains.') . '</p>';
    }
    return $output;
}
?>
