<?php
/**
 * @file
 * Sends Webform results to HubSpot's Leads API by using Webform's provided hooks.
 */

/**
 * Implement hook_menu() to get the config page listed
 */
function hubspot_menu() {
  $items = array();

  $items['admin/config/content/hubspot'] = array(
    'title' => 'HubSpot integration settings',
    'description' => 'Set up HubSpot integration and leads insertion.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('hubspot_admin_settings'),
    'access arguments' => array('administer site configuration'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'hubspot.admin.inc'
  );

  return $items;
}

/**
 * Intercept the WebForm submission and send it off to HubSpot.
 */
function hubspot_webform_submission_insert($node, $submission) {
  if ($submission->is_draft == 1)
    return;

  // Now, $submission->data is an array indexed by component ID.
  // We must find the matching field names.
  $values = array();
  
  $hubSpotURL = '';
  foreach ($submission->data as $cid => $data) {
    if ($node->webform['components'][$cid]['type'] == 'hubspot_url') {
      $hubSpotURL = $data['value'][0];
      continue; // omit HubSpot URL from POST
    }

    $component = $node->webform['components'][$cid]['form_key'];
    $values[$component] = implode(',', $data['value']);
  }

  if (empty($hubSpotURL)) {
    // We're only interested in forms with HubSpot URLs to POST to
    return;
  }

  // These fields must be submitted with each request
  $values['UserToken'] = isset($_COOKIE['hubspotutk']) ? $_COOKIE['hubspotutk'] : '';
  $values['IPAddress'] = ip_address();

  $r = hubspot_insert_lead($hubSpotURL, $values);

  if (empty($r['Error'])) {
    watchdog('hubspot', strip_tags($r['Data']), NULL, WATCHDOG_INFO);
  }
  else {
    watchdog('hubspot', 'cURL error when submitting HubSpot data: @error',
             array('@error' => $r['ErrorMessage']), WATCHDOG_ERROR);

    if (variable_get('hubspot_debug_on', 0)) {
      drupal_mail('hubspot', 'curl_error', variable_get('hubspot_debug_email', variable_get('site_mail', '')),
                  language_default(), array('errormsg' => $r['ErrorMessage'], 'hubspot_url' => $hubSpotURL,
                                            'node_title' => $node->title),
                  variable_get('site_mail', ''));
    }
  }
}

/**
 * Implements hook_mail() to send error messages to the administrator.
 */
function hubspot_mail($key, &$message, $params) {
  switch ($key) {
    case 'curl_error':
      $message['subject'] = t('HubSpot leads insertion error');
      $message['body'][] = t('When attempting to submit the form "@form" to HubSpot, a cURL error occurred.',
                             array('@form' => $params['node_title']));
      $message['body'][] = t('Error message: @message', array('@message' => $params['errormsg']));
      $message['body'][] = t('HubSpot POST URL: @url', array('@url' => $params['hubspot_url']));
      $message['body'][] = t('To adjust the debugging settings, visit @url',
                             array('@url' => url('admin/config/content/hubspot', array('absolute' => TRUE))));
      break;
  }
}

/**
 * Executes the HubSpot API POST to insert a lead
 *
 * @param string $formURL HubSpot-provided POST URL to submit to
 * @param array $fields Form fields, such as name and contact info
 *
 * @return array with fields Data, Error, ErrorMessage, and HTTPCode.
 *         Error and ErrorMessage are the cURL error number and message,
 *         respectively (Error = 0 if no error), and HTTPCode is the HTTP
 *         response code of the request.
 */
function hubspot_insert_lead($formURL, $fields) {
  $strPost = "";

  // Turn $fields into POST-compatible list of parameters
  foreach ($fields as $fieldName => $fieldValue) {
    $strPost .= urlencode($fieldName) . '=';
    $strPost .= urlencode($fieldValue);
    $strPost .= '&';
  }

  $strPost = rtrim($strPost, '&'); // nuke the final ampersand

  // intialize cURL and send POST data
  $ch = curl_init();
  curl_setopt($ch, CURLOPT_POST, TRUE);
  curl_setopt($ch, CURLOPT_POSTFIELDS, $strPost);
  curl_setopt($ch, CURLOPT_URL, $formURL);
  curl_setopt($ch, CURLOPT_RETURNTRANSFER, TRUE);
  
  $resp = array();
  $resp['Data'] = curl_exec($ch);
  $resp['Error'] = curl_errno($ch);
  $resp['ErrorMessage'] = curl_error($ch);
  $resp['HTTPCode'] = curl_getinfo($ch, CURLINFO_HTTP_CODE);

  curl_close($ch);

  return $resp;
}

/**
 * Create a WebForm component to contain the form's HubSpot POST URL.
 */
function hubspot_webform_component_info() {
  return array(
    'hubspot_url' => array(
      'label' => t('HubSpot POST URL'),
      'description' => t('A HubSpot API POST URL, to submit a form\'s contents to HubSpot Leads.'),
      'features' => array(
        'csv' => FALSE,
        'email' => FALSE,
        'title_display' => FALSE, // this prevents the "Display" field from being displayed while editing the component
        'required' => FALSE
      )
    )
  );
}

/**
 * Provide default values for this component.
 */
function _webform_defaults_hubspot_url() {
  return array(
    'name' => 'HubSpot POST URL',
    'form_key' => 'hubspot',
    'pid' => 0,
    'weight' => 0,
    'value' => '',
    'extra' => array(
    ),
  );
}

function _webform_edit_hubspot_url($component) {
  $form = array();

  // Disable Description box
  $form['extra']['description'] = array();

  $form['value'] = array(
    '#type' => 'textfield',
    '#title' => t('HubSpot POST URL'),
    '#description' => t('The API POST URL provided under HubSpot\'s Lead API settings for this form.'),
    '#default_value' => $component['value']
  );

  // Hide display options
  $form['display'] = array('#type' => 'markup');

  // Overwrite the "Label" field to provide a better description
  $form['name'] = array(
    '#type' => 'textfield',
    '#default_value' => $component['name'],
    '#title' => t('Label'),
    '#description' => t('The name of this field. This field will not be displayed to users submitting the form.'),
    '#required' => TRUE,
    '#weight' => -10,
    '#maxlength' => 255,
  );

  return $form;
}

/**
 * Implements _webform_render_component(). Render this as a hidden field.
 */
function _webform_render_hubspot_url($component, $value = NULL) {
  $element = array(
    '#type' => 'hidden',
    '#title' => check_plain($component['name']),
    '#value' => $component['value'],
    '#weight' => $component['weight'],
  );

  if (isset($value[0])) {
    $element['#default_value'] = $value[0];
  }

  return $element;
}

/**
 * When displaying the form results to an admin, don't bother showing the HubSpot URL.
 */
function _webform_display_hubspot_url($component, $value, $format = 'html') {
  return array();
}

/**
 * Implementation of hook_page_build() to inject the HubSpot JavaScript tracking code into
 * the page footer, just before </body>.
 */
function hubspot_page_build(&$page) {
  $page['page_bottom']['hubspot_code'] = array(
    '#type' => 'markup',
    '#markup' => variable_get('hubspot_log_code', '')
  );
}

/**
 * Implementation of hook_help() for the admin help page.
 */
function hubspot_help($path, $arg) {
  $output = '';
  switch ($path) {
    case 'admin/help#hubspot':
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('The HubSpot module provides leads integration with the HubSpot API, allowing forms created with the Webform module to submit their data to HubSpot for leads tracking.') . '</p>';

      $output .= '<h3>' . t('Sending a form to HubSpot') . '</h3>';
      $output .= '<p>' . t('To have a form\'s data sent to HubSpot for leads tracking, complete the following steps:') . '</p>';
      $output .= '<ul>';
      $output .= '<li>' . t('Log in to your HubSpot account and visit the Settings page. Click the HubSpot Lead API link under Lead Management.') . '</li>';
      $output .= '<li>' . t('Press Add New Form and specify the form name, email list, and lead nurturing campaign as desired.') . '</li>';
      $output .= '<li>' . t('Submit the form. HubSpot will now provide an API POST URL; save this somewhere.') . '</li>';
      $output .= '<li>' . t('In your Drupal admin, use the Add content page to create a new Webform. Enter as many questions ("components") as you\'d like.') . '</li>';
      $output .= '<li>' . t('Finally, create a component named "hubspot" with the type "HubSpot POST URL". Supply the API POST URL in the box provided and save the form.') . '</li>';
      $output .= '</ul>';
      $output .= '<p>' . t('The Webform will now automatically send any submissions directly to HubSpot via the POST URL you provided. You may customize, theme, or alter the form as much as you like, so long as the HubSpot POST URL field remains.') . '</p>';
      $output .= '<p>' . t('Please note that HubSpot applies a 500-character limit to each form field submitted, so you may want to set the "Maxlength" setting on the Webform fields appropriately.') . '</p>';

      $output .= '<h3>' . t('Form field names') . '</h3>';
      $output .= '<p>' . t('Certain form field keys have significance with HubSpot. For example, submitting a field with the key "FirstName" allows HubSpot to automatically recognize it as the person\'s first name when displaying the lead information. Here is a list of HubSpot-recognized field keys:') . '</p>';
      $output .= '<dl>';
      $output .= '<dt>' . t('FirstName, LastName, and FullName') . '</dt>';
      $output .= '<dd>' . t('Use FirstName or LastName to send those fields separately; send FullName for HubSpot to automatically split the name into first and last names.') . '</dd>';
      $output .= '<dt>' . t('Email, Phone, Fax, Website, and TwitterHandle') . '</dt>';
      $output .= '<dd>' . t('Specify these field keys to get the user\'s contact information recognized by HubSpot.') . '</dd>';
      $output .= '<dt>' . t('Company, NumberEmployees, AnnualRevenue, and JobTitle') . '</dt>';
      $output .= '<dd>' . t('Capture the user\'s employment information.') . '</dd>';
      $output .= '<dt>' . t('Address, City, State, ZipCode, Country') . '</dt>';
      $output .= '<dd>' . t('Capture the user\'s location.') . '</dd>';
      $output .= '<dt>' . t('Message') . '</dt>';
      $output .= '<dd>' . t('Allow the user to send a custom message.') . '</dd>';
      $output .= '</dl>';
      $output .= '<p>' . t('Specify these as the <strong>Field Key</strong> when adding components in your form. The field key is not shown to users filling out the form, but only sent to HubSpot; the "Label" field specifies what your users will see.') . '</p>';
      $output .= '<p>' . t('Note that you may provide other custom fields with any field key you like, if you have other data you wish to collect. HubSpot will store all data sent to it and display it in the "Form Data" tab when viewing each lead.') . '</p>';
      
      $output .= '<h3>' . t('HubSpot Javascript tracking code') . '</h3>';
      $output .= '<p>' . t('HubSpot supports using a JavaScript tracking system to analyze potential leads on your site. You can get the JavaScript code from your HubSpot settings, under External Site Traffic Logging, and paste it into the HubSpot integration settings page in Drupal to have it automatically included on every page.') . '</p>';
      break;
  }
  return $output;
}
